[package]
name = "citrus"
version = "0.1.0"
edition = "2021"

[dependencies]
citrus_core = { path = "./citrus_core" }
tokio = { version = "1", features = ["full"] }
png = "0.17.13"
rand = "0.8.5"

[workspace]
members = [
    "citrus_core/"
]
